[theme]
base="dark"
primaryColor="#5DADE2"  # soft sky blue for accents
backgroundColor="#1C1F24"  # dark blue-gray background
secondaryBackgroundColor="#2C3036"  # mid-tone blue-gray for containers
textColor="#E8EDF1"  # very light blue-gray text
font="sans serif"
