[theme]
base="dark"
primaryColor="#8FBCBB"  # soft bluish-gray accent
backgroundColor="#1e1e1e"  # dark charcoal gray
secondaryBackgroundColor="#2e2e2e"  # slightly lighter for panels
textColor="#e0e0e0"  # light gray for text
font="sans serif"
